name = "CallistoVisualization"
authors = ["Sanjay Lall <sanjaylall@google.com>"]
uuid = "4bf5cafc-e35d-4b43-8dcc-f87515cd361a"
version = "0.1.0"


[deps]
PlotKit = "003d7de4-8e60-4dbf-84f8-37f925e78aff"
Callisto = "4ae4e7f3-3a0d-47fd-9705-768e0f1baff0"


